TUNE_VAR_LIST = {
    1 : {
        CH : <% ReadPLC("AItoACP[1]"); %>,
        PV : <% ReadPLC("AI[1].PV"); %>,
        ST : <% ReadPLC("AI[1].STATUS"); %>,
        SL : <% ReadPLC("AI[1].SL"); %>,
        SH : <% ReadPLC("AI[1].SH"); %>,
        VLL : <% ReadPLC("AI[1].VLL"); %>,
        VL : <% ReadPLC("AI[1].VL"); %>,
        VH : <% ReadPLC("AI[1].VH"); %>,
        VHH : <% ReadPLC("AI[1].VHH"); %>,
        CUR : <% ReadPLC("AI[1].CUR"); %>,
        VMAN : <% ReadPLC("AI[1].VMAN"); %>,
        EMAN : <% ReadPLC("AI[1].EMAN"); %>,
    },
    2 : {
        CH : <% ReadPLC("AItoACP[2]"); %>,
        PV : <% ReadPLC("AI[2].PV"); %>,
        ST : <% ReadPLC("AI[2].STATUS"); %>,
        SL : <% ReadPLC("AI[2].SL"); %>,
        SH : <% ReadPLC("AI[2].SH"); %>,
        VLL : <% ReadPLC("AI[2].VLL"); %>,
        VL : <% ReadPLC("AI[2].VL"); %>,
        VH : <% ReadPLC("AI[2].VH"); %>,
        VHH : <% ReadPLC("AI[2].VHH"); %>,
        CUR : <% ReadPLC("AI[2].CUR"); %>,
        VMAN : <% ReadPLC("AI[2].VMAN"); %>,
        EMAN : <% ReadPLC("AI[2].EMAN"); %>,
    },
    3 : {
        CH : <% ReadPLC("AItoACP[3]"); %>,
        PV : <% ReadPLC("AI[3].PV"); %>,
        ST : <% ReadPLC("AI[3].STATUS"); %>,
        SL : <% ReadPLC("AI[3].SL"); %>,
        SH : <% ReadPLC("AI[3].SH"); %>,
        VLL : <% ReadPLC("AI[3].VLL"); %>,
        VL : <% ReadPLC("AI[3].VL"); %>,
        VH : <% ReadPLC("AI[3].VH"); %>,
        VHH : <% ReadPLC("AI[3].VHH"); %>,
        CUR : <% ReadPLC("AI[3].CUR"); %>,
        VMAN : <% ReadPLC("AI[3].VMAN"); %>,
        EMAN : <% ReadPLC("AI[3].EMAN"); %>,
    },
    4 : {
        CH : <% ReadPLC("AItoACP[4]"); %>,
        PV : <% ReadPLC("AI[4].PV"); %>,
        ST : <% ReadPLC("AI[4].STATUS"); %>,
        SL : <% ReadPLC("AI[4].SL"); %>,
        SH : <% ReadPLC("AI[4].SH"); %>,
        VLL : <% ReadPLC("AI[4].VLL"); %>,
        VL : <% ReadPLC("AI[4].VL"); %>,
        VH : <% ReadPLC("AI[4].VH"); %>,
        VHH : <% ReadPLC("AI[4].VHH"); %>,
        CUR : <% ReadPLC("AI[4].CUR"); %>,
        VMAN : <% ReadPLC("AI[4].VMAN"); %>,
        EMAN : <% ReadPLC("AI[4].EMAN"); %>,
    },
    5 : {

        CH : <% ReadPLC("AItoACP[5]"); %>,
        PV : <% ReadPLC("AI[5].PV"); %>,
        ST : <% ReadPLC("AI[5].STATUS"); %>,
        SL : <% ReadPLC("AI[5].SL"); %>,
        SH : <% ReadPLC("AI[5].SH"); %>,
        VLL : <% ReadPLC("AI[5].VLL"); %>,
        VL : <% ReadPLC("AI[5].VL"); %>,
        VH : <% ReadPLC("AI[5].VH"); %>,
        VHH : <% ReadPLC("AI[5].VHH"); %>,
        CUR : <% ReadPLC("AI[5].CUR"); %>,
        VMAN : <% ReadPLC("AI[5].VMAN"); %>,
        EMAN : <% ReadPLC("AI[5].EMAN"); %>,
    },
    6 : {
        CH : <% ReadPLC("AItoACP[6]"); %>,
        PV : <% ReadPLC("AI[6].PV"); %>,
        ST : <% ReadPLC("AI[6].STATUS"); %>,
        SL : <% ReadPLC("AI[6].SL"); %>,
        SH : <% ReadPLC("AI[6].SH"); %>,
        VLL : <% ReadPLC("AI[6].VLL"); %>,
        VL : <% ReadPLC("AI[6].VL"); %>,
        VH : <% ReadPLC("AI[6].VH"); %>,
        VHH : <% ReadPLC("AI[6].VHH"); %>,
        CUR : <% ReadPLC("AI[6].CUR"); %>,
        VMAN : <% ReadPLC("AI[6].VMAN"); %>,
        EMAN : <% ReadPLC("AI[6].EMAN"); %>,
    },
    7 : {
        CH : <% ReadPLC("AItoACP[7]"); %>,
        PV : <% ReadPLC("AI[7].PV"); %>,
        ST : <% ReadPLC("AI[7].STATUS"); %>,
        SL : <% ReadPLC("AI[7].SL"); %>,
        SH : <% ReadPLC("AI[7].SH"); %>,
        VLL : <% ReadPLC("AI[7].VLL"); %>,
        VL : <% ReadPLC("AI[7].VL"); %>,
        VH : <% ReadPLC("AI[7].VH"); %>,
        VHH : <% ReadPLC("AI[7].VHH"); %>,
        CUR : <% ReadPLC("AI[7].CUR"); %>,
        VMAN : <% ReadPLC("AI[7].VMAN"); %>,
        EMAN : <% ReadPLC("AI[7].EMAN"); %>,
    },
    8 : {
        CH : <% ReadPLC("AItoACP[8]"); %>,
        PV : <% ReadPLC("AI[8].PV"); %>,
        ST : <% ReadPLC("AI[8].STATUS"); %>,
        SL : <% ReadPLC("AI[8].SL"); %>,
        SH : <% ReadPLC("AI[8].SH"); %>,
        VLL : <% ReadPLC("AI[8].VLL"); %>,
        VL : <% ReadPLC("AI[8].VL"); %>,
        VH : <% ReadPLC("AI[8].VH"); %>,
        VHH : <% ReadPLC("AI[8].VHH"); %>,
        CUR : <% ReadPLC("AI[8].CUR"); %>,
        VMAN : <% ReadPLC("AI[8].VMAN"); %>,
        EMAN : <% ReadPLC("AI[8].EMAN"); %>,
    },
    9 : {
        CH : <% ReadPLC("AItoACP[9]"); %>,
        PV : <% ReadPLC("AI[9].PV"); %>,
        ST : <% ReadPLC("AI[9].STATUS"); %>,
        SL : <% ReadPLC("AI[9].SL"); %>,
        SH : <% ReadPLC("AI[9].SH"); %>,
        VLL : <% ReadPLC("AI[9].VLL"); %>,
        VL : <% ReadPLC("AI[9].VL"); %>,
        VH : <% ReadPLC("AI[9].VH"); %>,
        VHH : <% ReadPLC("AI[9].VHH"); %>,
        CUR : <% ReadPLC("AI[9].CUR"); %>,
        VMAN : <% ReadPLC("AI[9].VMAN"); %>,
        EMAN : <% ReadPLC("AI[9].EMAN"); %>,
    },
}

USER = '<% EnvPrint(LOGIN_USERNAME); %>';